# Generated by Django 5.2.3 on 2025-07-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_book_options_customuser'),
    ]

    operations = [
    ]
