# Generated by Django 5.2.3 on 2025-09-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='accounts.customuser')),
            ],
        ),
    ]
