# Generated by Django 5.2.3 on 2025-07-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_year',
            new_name='publication_year',
        ),
    ]
