# Generated by Django 5.2.4 on 2025-07-18 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default=datetime.date(1990, 1, 1)),
        ),
    ]
